#!/bin/sh
# meshapi installer  —  macOS & Linux
#
#   curl -fsSL https://cli.meshapi.ai/install.sh | sh
#
# Installs uv (a single static binary that brings its own Python), then
# `uv tool install meshapi-code`, fixes PATH, and launches meshapi. Nothing
# needs to be preinstalled — no Python, no pipx. Re-running upgrades an
# existing install.
#
# Source: https://github.com/aifiesta/meshapi-code/blob/main/install.sh
# Inspect before piping to a shell — this file is short on purpose.
set -eu

PKG="meshapi-code"
UV_VERSION="0.12.2"   # pinned for supply-chain safety; bump deliberately

info() { printf '\033[36m%s\033[0m\n' "$*"; }
warn() { printf '\033[33m%s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31merror: %s\033[0m\n' "$*" >&2; exit 1; }

# --- make uv (and its tool shims) reachable in THIS shell -----------------
# uv installs to ~/.local/bin on current releases; older uv used ~/.cargo/bin.
# It also drops an env script that puts its bin dir on PATH — source it if it
# exists (guard -u: env files reference vars we haven't set).
ensure_uv_on_path() {
  for d in "$HOME/.local/bin" "$HOME/.cargo/bin"; do
    case ":$PATH:" in
      *":$d:"*) ;;
      *) [ -d "$d" ] && PATH="$d:$PATH" ;;
    esac
  done
  if [ -f "$HOME/.local/bin/env" ]; then
    set +u
    # shellcheck disable=SC1091  # env script is generated by uv at install time
    . "$HOME/.local/bin/env"
    set -u
  fi
  export PATH
}

command -v curl >/dev/null 2>&1 || die "curl is required (install it, then re-run)."

ensure_uv_on_path
if ! command -v uv >/dev/null 2>&1; then
  info "Installing uv (Python bootstrapper)…"
  # Pinned, HTTPS, its own curl|sh — independent of this script's stdin.
  curl -fsSL "https://astral.sh/uv/${UV_VERSION}/install.sh" | sh \
    || die "uv install failed — see https://docs.astral.sh/uv/getting-started/installation/"
  ensure_uv_on_path
fi
command -v uv >/dev/null 2>&1 \
  || die "uv is installed but not on PATH — open a new terminal and re-run this command."

# --- detect a non-uv meshapi ANYWHERE on PATH that could shadow ours -------
# `command -v` returns only the FIRST match — on an upgrade that's our own
# freshly-prepended uv copy, which hides an OLDER copy (e.g. a python.org
# framework `pip install`) still sitting earlier on PATH for NEW shells. Scan
# every PATH entry, skipping our own dirs.
shadow_path=""
set -f            # PATH components must not glob-expand when we word-split them
IFS=:
# shellcheck disable=SC2086  # deliberate word-split of PATH on ':'
for d in $PATH; do
  [ -n "$d" ] || continue
  [ -x "$d/meshapi" ] || continue
  case "$d/meshapi" in
    *uv/tools*|*/.local/bin/meshapi|*/.cargo/bin/meshapi) : ;;
    *) shadow_path="$d/meshapi"; break ;;
  esac
done
unset IFS         # restore default word-splitting for the rest of the script
set +f

# --- install, or upgrade if already present (idempotent) ------------------
if uv tool list 2>/dev/null | grep -q "^${PKG} "; then
  info "Upgrading ${PKG}…"
  uv tool upgrade "${PKG}" || die "upgrade failed"
else
  info "Installing ${PKG}…"
  uv tool install "${PKG}" || die "install failed"
fi

# Persist PATH for future shells, then refresh this one so the launch below
# and a plain `meshapi` both work without reopening the terminal.
uv tool update-shell >/dev/null 2>&1 || true
ensure_uv_on_path
command -v meshapi >/dev/null 2>&1 || die "meshapi not found after install."

info "✓ $(meshapi --version 2>/dev/null || echo "${PKG} installed")"

# A prior `pip install meshapi-code` (often a python.org framework build) can
# sit EARLIER on PATH than uv's dir, so in a NEW terminal `meshapi` runs the
# STALE copy and dies with "No API key found … edit config.json" even though
# this install succeeded — the single most confusing failure mode. When we
# detect that, DON'T launch into a copy the user can't re-launch (that reads as
# "it worked once, then broke"); explain the fix and how to start instead.
if [ -n "$shadow_path" ]; then
  warn ""
  warn "⚠ Installed — but another meshapi is EARLIER on your PATH and will win:"
  warn "    $shadow_path"
  warn "  Your 'meshapi' command runs that OLD copy (symptom: 'No API key found')."
  warn "  Remove it, then open a new terminal:"
  warn "    \"${shadow_path%/meshapi}/python3\" -m pip uninstall meshapi-code"
  warn "  After that, just run:  meshapi"
# --- otherwise launch on the controlling terminal, else print how to start -
# In `curl … | sh`, this script's stdin is the pipe (not a TTY), so meshapi's
# first-run key prompt would exit immediately. Reconnect stdin to the real
# terminal, gated on an interactive session ([ -t 1 ] => a human is watching).
# `exec` as the last statement means sh never reads more of the piped script.
elif [ -t 1 ] && [ -r /dev/tty ]; then
  info "Launching meshapi… (first run asks for your rsk_ API key)"
  exec meshapi </dev/tty
else
  info "Installed. Start it any time with:  meshapi"
  info "(If 'meshapi' isn't found, open a new terminal first.)"
fi
